config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home", as: "home"
  get "/dashboard" => "pages#dashboard", as: "dashboard"

  get "/categories" => "categories#index", as: "categories"
  get "/categories/new" => "categories#new", as: "new_category"
  post "/categories" => "categories#create", as: "create_category"
  get "/categories/:id/edit" => "categories#edit", as: "edit_category"
  patch "/categories/:id" => "categories#update", as: "update_category"
  delete "/categories/:id" => "categories#destroy", as: "destroy_category"
  get "/categories/:id" => "categories#show", as: "show_category"

  get "/tasks" => "tasks#index", as: "tasks"
  get "/tasks/new" => "tasks#new", as: "new_task"
  post "/tasks" => "tasks#create", as: "create_task"
  get '/tasks/:id' => 'tasks#show', as: 'show_task'
  get '/tasks/:id/edit' => 'tasks#edit', as: 'edit_task'
  patch '/tasks/:id' => 'tasks#update', as: 'update_task'
  delete '/tasks/:id' => 'tasks#destroy', as: 'destroy_task'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :name, :body, :date, :user_id, :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, :dependent => :destroy
  has_many :tasks, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: %i[ show edit update destroy ]
    before_action :authenticate_user!

    def index
        @categories = current_user.categories
    end

    def new
        @category = Category.new
    end

    def create
        @category = current_user.categories.build(category_params)
        
        if @category.save
            redirect_to dashboard_path
            flash[:success] = "Category created!"
        else
            render :new, status: 422
        end
    end

    def show
        @category = Category.find(params[:id])
        @tasks = @category.tasks
    end
  
    
    def edit
            @category = Category.find(params[:id])
    end

    def destroy
            @category = Category.find(params[:id])
            @category.destroy
            redirect_to dashboard_path
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            redirect_to categories_path
         else
            render :edit, status: 422
         end

    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def set_category
        @category = Category.find(params[:id])
      end
        
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!, except:  [:home]
    def home
    end

    def dashboard
        @user = current_user
        @selected_date = params[:selected_date] ? Date.parse(params[:selected_date]) : Date.current
        @tasks_by_category = current_user.tasks.where(date: @selected_date.beginning_of_day..@selected_date.end_of_day).group_by(&:category)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!

    def index
        @tasks = current_user.tasks
    end

    def new
        @task = Task.new
        @categories = current_user.categories
    end

    def create
            @task = current_user.tasks.build(task_params)
            if @task.save
                redirect_to dashboard_path
                flash[:success] = "Task created!"
            else
                render :new, status: 422
            end
        end

    def show
        @task = Task.find(params[:id])
        @tasks = current_user.tasks
    end
 
    def edit
        @task = Task.find(params[:id])
        @categories = current_user.categories
    end

    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
            redirect_to dashboard_path
            flash[:success] = "Task updated!"
        else
            render :edit, status: 422
        end

    end
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to dashboard_path
    end

    private

    def task_params
        params.require(:task).permit(:name, :body, :date, :user_id, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
<%= render "/pages/nav" %>
<div class="container-fluid" >
    <div class="row main-content bg-color text-center">
        <div class=" text-center p-5 text-light">
            <h2 class="font">Edit Category </h2> 
            <hr> <br>

            <%= form_with model: @category, url: update_category_path(@category), local: true do |f| %>

            <p>
            <%= f.text_field :name, class: "form_input fields", placeholder: "Enter category name" %>
        </p>

        <p>
            <%= f.submit class: "btn btn-success" %>
        </p>

        </div>

            <% end %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<%= render "/pages/nav" %>
<div class="container-fluid">
<div class="row main-content bg-color text-center p-5 text-light">
<h2 class="text-dark"> Categories </h2>
<hr>
<% if @categories.present? %>
<% @categories.each do |cat|  %>
<div>
    <h5> <%= link_to cat.name, show_category_path(cat.id), class: "text-decoration-none text-dark" %> <%= link_to "Edit", edit_category_path(cat), class: "btn btn-warning" %> </h5>
    <hr>
    </div>
<% end %>
<% else %>
    <p> No category available </p>
<% end %>
<div>
<br>
<%= link_to "Create new category", new_category_path, class: "btn btn-success" %>
</div>
</div>
</div>

app/views/categories/new.html.erb
<%= render "/pages/nav" %>
<div class="container-fluid">
    <div class="row main-content bg-color text-center p-5 text-light">
        <h1 class="font">Create Category</h1>
        <%= form_with scope: :category, url: create_category_path, class: "form-group text-success p-4", local: true do |f| %>

        <p>
            <%= f.text_field :name, class: "form_input fields", placeholder: "Enter category name" %>
        </p>

        <p>
            <%= f.submit class: "btn btn-success" %>
        </p>
        <% end %>

    </div>
</div>

app/views/categories/show.html.erb
<%= render "/pages/nav" %>
<div class="container-fluid" >
    <div class="row main-content bg-color text-center">
        <div class=" text-center p-5">
            <h2> <%= @category.name %> </h2>
      
                <table class="table">
            <thead>
                <tr>
                <th scope="col">Task</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Date</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            <% if @tasks.present? %>
            <% @tasks.each do |task, category| %>
                    <tr>
                    <th scope="row"><%= task.name %></th>
                    <td><%= task.category.name %></td>
                    <td><%= task.body %></td>
                    <td><%= task.date %></td>
                    <td><%= link_to "Edit", edit_task_path(task), class: "btn btn-warning" %>
                <%= link_to "Delete", destroy_task_path(task), method: :delete, class: "btn btn-danger" %></td>
                </tr>

                <% end %>
             <% else %>
             <tr>
                 <td colspan="5">No Tasks </td>
             </tr> 
             <tr>
                  <td colspan="5"><%= link_to "Add Task",  new_task_path, class: "btn btn-warning" %></td>
             </tr>     
               
             <% end %>
            </tbody>
            </table>
      <%= link_to 'Back to Categories', categories_path, class: "btn btn-success" %>
 
        </div>    
      
    </div>
</div>          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/pages/_nav.html.erb
<div class="cointainer-fluid text-center abc bg-light p-3" >
    <h1 class = "home-title1 ">
     <%= link_to "TaskSync", dashboard_path, class: "text-decoration-none text-dark"  %>  
     </h1>
    <div class="position-absolute top-0 end-0 p-3">
    <%= button_to "logout", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    </div>
</div>

app/views/pages/dashboard.html.erb
<%= render "/pages/nav" %>
<div class= "d-flex flex-column align-items-center vw-100 "  >
  <div class="text-center">
    <br>
    <h5>Welcome to your Dashboard,
    <%= @user.name %>!</h5>
    <br>
     
    <br>
    <%= form_with url: dashboard_path, method: :get do |f| %> 
      <p>
      <%= f.date_field :selected_date, value: @selected_date, class: "p-2 rounded-3 border border-light " %>
      <%= f.submit "Submit", class: "btn btn-success" %>
      </p>
    <% end %>

    <div class="container-lg" >
    <div class=" bg-color p-5 ">
    <% if @tasks_by_category.present? %>
     
    <table class="table">
  <thead>
    <tr>
      <th scope="col">Task</th>
      <th scope="col">Category</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @tasks_by_category.each do |category, tasks| %>
       <% tasks.each do |task| %>
          <tr>
          <th scope="row"><%= task.name %></th>
        <td><%= task.category.name %></td>
        <td><%= task.body %></td>
        <td><%= task.date %></td>
        <td><%= link_to "Edit", edit_task_path(tasks), class: "btn btn-warning" %>
      <%= link_to "Delete", destroy_task_path(tasks), method: :delete, class: "btn btn-danger" %></td>
      </tr>
      <% end %>
      <% end %>
  </tbody>
</table>
   
      
    
    <% else %>
    <h5>No Task Found</h5>
    <p>
        <%= link_to "Add new task", new_task_path, class: "text-decoration-none" %>
    </p>
    <% end %>

</div>
   
  </div>

  <div class="d-flex justify-content-evenly p-5">
    <p><%= link_to "Manage Categories", categories_path, class: "btn btn-dark" %></p>
    <p><%= link_to "View All Tasks", tasks_path, class: "btn btn-dark" %></p>
    <p><%= link_to "Add new task", new_task_path, class: "btn btn-dark" %></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="d-flex flex-column justify-content-center align-items-center vh-100 vw-100 home">
    <h1 class = "home-title "> TaskSync </h1>
    <h3 class = "home-sub"> Sync Your Way to Productivity! </h3>    
    <br>
    <%= link_to "Sync Your Tasks", dashboard_path, class: "btn btns btn-lg " %>
    
</div>

app/views/pages/try.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal">
    <h1>New post</h1>
    <br>
    <div>
      <%= link_to "Cancel", "#", data: {
        controller: "modals",
        action: "modals#close"
      }, class: "cancel-button" %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render "/pages/nav" %>
<div class="container-fluid" >
    <div class="row main-content bg-color text-center">
        <div class=" text-center p-5 text-light">
            <h2 class="font">Edit Task </h2> 
            <hr> <br>

            <%= form_with model: @task, url: update_task_path(@task), local: true do |f| %>

            <p>
                <%= f.text_field :name, placeholder: "Task Name", class: "form__input fields", required: true %>
            </p>

            <p>
                <%= f.text_area :body, placeholder: "Description", class: "form__input fields", required: true %>
            </p>
        <div class="d-flex justify-content-around">
            <p>
            <%= f.label :date, "Task Date:" %><br>
                <%= f.date_field :date, required: true %>
            </p>

            <p>
    <%= f.label :category_id, "Category" %><br>
    <%= f.select :category_id, options_from_collection_for_select(@categories, :id, :name), class: "form-select form-select-lg mb-3", required: true%>
  </p>
        </div>
            <p class="p-3">
                <%= f.submit "Save", class: "btn btn-success"  %>
                <%= link_to "Cancel", dashboard_path, class: "btn btn-warning"  %>
            </p>

            <% end %>
        </div>
    </div>
</div>

app/views/tasks/index.html.erb
<%= render "/pages/nav" %>
<div class="container-fluid" >
    <div class="row main-content bg-color text-center">
        <div class=" text-center p-5">
            <h2 > Tasks </h2>
          
        <%= link_to "Add new task", new_task_path, class: "btn btn-success" %>
        <% if @tasks.present? %>
                
                <table class="table">
            <thead>
                <tr>
                <th scope="col">Task</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Date</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            <% @tasks.each do |task, category| %>
                    <tr>
                    <th scope="row"><%= task.name %></th>
                    <td><%= task.body %></td>
                    <td><%= task.category.name %></td>
                    <td><%= task.date %></td>
                    <td><%= link_to "Edit", edit_task_path(task), class: "btn btn-warning" %>
                <%= link_to "Delete", destroy_task_path(task), method: :delete, class: "btn btn-danger" %></td>
                </tr>

                <% end %>
            </tbody>
            </table>

    <% else %>
    <h5>No Task Found</h5>
    <p>
        <%= link_to "Add new task", new_task_path, class: "text-decoration-none" %>
    </p>
    <% end %>
        </div>    

    </div>
</div>          

app/views/tasks/new.html.erb
<%= render "/pages/nav" %>
<div class="container-fluid" >
    <div class="row main-content bg-color text-center">
        <div class=" text-center p-5 text-light">
            <h2 class="font"> Add new Task </h2> 
            <hr> <br>

            <%= form_with scope: :task, url: create_task_path, local: true do |f| %>

            <p>
                <%= f.text_field :name, placeholder: "Task Name", class: "form__input fields", required: true %>
            </p>

            <p>
                <%= f.text_area :body, placeholder: "Task description", class: "form__input fields", required: true %>
            </p>
        <div class="d-flex justify-content-around">
            <p>
            <%= f.label :date, "Task Date:" %><br>
                <%= f.date_field :date, required: true %>
            </p>

            <p>
    <%= f.label :category_id, "Category" %><br>
    <%= f.select :category_id, options_from_collection_for_select(@categories, :id, :name), class: "form-select form-select-lg mb-3", required: true%>
  </p>
        </div>
            <p class="p-3">
                <%= f.submit "Save", class: "btn btn-success"  %>
                <%= link_to "Cancel", dashboard_path, class: "btn btn-warning"  %>
            </p>

            <% end %>
        </div>
    </div>
</div>

app/views/tasks/show.html.erb
<h3>
   <%= @task.name %><br>
   <%= @task.body %>
   <%= link_to 'Edit', edit_task_path %> |
</h3>



<%= link_to 'Back to Categories', categories_path %>